effects={
    "迅捷": "speed",
    "缓慢": "slowness",
    "急迫": "haste",
    "挖掘疲劳": "mining_fatigue",
    "力量": "strength",
    "瞬间治疗": "instant_health",
    "瞬间伤害": "instant_damage",
    "跳跃提升": "jump_boost",
    "反胃": "nausea",
    "生命恢复": "regeneration",
    "抗性提升": "resistance",
    "抗火": "fire_resistance",
    "水下呼吸": "water_breathing",
    "隐身": "invisibility",
    "失明": "blindness",
    "夜视": "night_vision",
    "饥饿": "hunger",
    "虚弱": "weakness",
    "中毒": "poison",
    "凋零": "wither",
    "生命提升": "health_boost",
    "伤害吸收": "absorption",
    "饱和": "saturation",
    "发光": "glowing",
    "飘浮": "levitation",
    "幸运": "luck",
    "霉运": "unluck",
    "缓降": "slow_falling",
    "潮涌能量": "conduit_power",
    "海豚的恩惠": "dolphins_grace",
    "不祥之兆": "bad_omen",
    "村庄英雄":  "hero_of_the_village",
    "黑暗": "darkness",
    "试炼之兆": "trial_omen",
    "袭击之兆": "raid_omen",
    "蓄风": "wind_charged",
    "盘丝":"weaving",
    "渗浆":"oozing",
    "寄生":"infested"
}